**Zadanie domowe!**

Napisz prostą grę w zgadywanie liczby. Gra polega na wylosowaniu przez program dowolnej liczby czterocyfrowej z przedziału [1000, 9999]. Zadaniem gracza jest odgadnięcie tej liczby poprzez wpisanie jej. Po wpisaniu liczby przez gracza program może działać w dwóch wersjach:<br>
1. Wersja prostsza.<br>
Program podświetla na zielono wszystkie cyfry, które zostały wpisane na prawidłowych miejscach, a reszta cyfr zostaje wyświetlona bez zmian.<br>
<br>
Przykład działania:<br>
Wprowadź liczbę: $1111$<br>
$1111$<br>
Wprowadź liczbę: $2222$<br>
$2222$<br>
Wprowadź liczbę: $3333$<br>
$3333$<br>
Wprowadź liczbę: $4444$<br>
$444\color{green}{4}$<br>
Wprowadź liczbę: $5555$<br>
$5555$<br>
Wprowadź liczbę: $6666$<br>
$66\color{green}{6}6$<br>
Wprowadź liczbę: $7777$<br>
$\color{green}{77}77$<br>
Wprowadź liczbę: $7764$<br>
$\color{green}{7764}$<br>
<br>
2. Wersja trudniejsza:<br>
Program podświetla na zielono liczby tak jak w punkcie 1. ale dodatkowo podświetla na żółto/ pomarańczowo liczby, które znajdują się w rozwiązaniu, ale są na złej pozycji.<br>
<br>
Przykład działania:<br>
Wprowadź liczbę: $1234$<br>
$\color{green}{1}2\color{orange}{3}4$<br>
Wprowadź liczbę: $5678$<br>
$\color{orange}{5}678$<br>
Wprowadź liczbę: $9033$<br>
$\color{orange}{9}0\color{orange}{3}3$<br>
Wprowadź liczbę: $1593$<br>
$\color{green}{1}\color{orange}{5}\color{green}{9}\color{orange}{3}$<br>
Wprowadź liczbę: $1395$<br>
$\color{green}{1395}$<br>
<br>
Zwróć uwagę, że w przypadku gdy podana była liczba $9033$ tylko jedna cyfra $3$ została podświetlona, bo tylko jedna znajdowała się w rozwiązaniu!

Do kolorowania teksu przyda się biblioteka `termcolor`, a dokładnie jej funkcja `colored`. Przykład działania został zaprezentowany poniżej.

In [14]:
from termcolor import colored

print(colored('Ala', 'red'), colored('ma', 'yellow'), colored('kota', 'green'))

Ala ma kota


Dodatkowo, program ma sprawdzać, czy dane podane przez użytkownika rzeczywiście są czterocyfrową liczbą z przedziału [1000, 9999]. Jeśli nie, ma zostać wyświetlony komunikat `Podane wyrażenie jest nieprawidłowe!` po czym program ma działać dalej normalnie i prosić o wprowadzenie liczby.

W celu ułatwienia zadania polecam skorzystać z podanego poniżej szkieletu programu zawierającego proponowany sposób rozwiązania za pomocą funkcji.

In [ ]:
from random import randint #funkcja randint(a, b) zwraca losową liczbę całkowitą z przedziału [a, b]
from termcolor import colored #funkcja colored(tekst, kolor) zwraca tekst o podanym kolorze (w funkcji print!)

def generateNumber():
    '''Funkcja losująca liczbę z przedziału [1000, 9999]. Zwraca wartość w typie ciągu znaków (str).'''

def isWin(user, goal):
    '''Funkcja sprawdzająca czy liczba podana przez użytkownika (user) jest taka sama jak liczba,
    która ma zostać zgadnięta (goal). Jeśli tak, zwróć True, jeśli nie, zwróć False.'''

def isCorrect(user):
    '''Funkcja sprawdzająca, czy podana przez użytkownika liczba jest prawidłowa, 
    czyli czy jest czterocyfrowa z przedziału [1000, 9999]. Jeśli jest prawidłowa, zwróć True, 
    w przeciwnym razie zwróć False.'''

def showResult(user, goal):
    '''Funkcja wyświetlajaca odpowiednio pokolorowaną liczbę (user) po porównaniu jej z liczbą 
    do zgadnięcia (goal). Tylko ta funkcja będzie się zmieniała w zależności od tego, która wersja gry
    została wybrana do zrobienia.'''
    
goal = generateNumber() #wywołanie funkcji generującej liczbę do zgadnięcia
win = False #zmienna przechowująca informację, czy gracz już wygrał
while not win: #jeśli gracz nie wygrał, czyli win = False, pętla kontynuuje działanie
    user = input('Wprowadź liczbę: ') #instrukcja pobierająca liczbę od użytkownika
    if isCorrect(user): #wywołanie funkcji sprawdzającej czy podana liczba jest prawidłowa
        showResult(user, goal) #jeśli jest prawidłowa, wywoływana jest funkcja wyświetlająca odpowiednie kolory cyfr
    else: #jeśli funkcja isCorrect zwróciła False, wyświetlany jest poniższy tekst
        print('Podane wyrażenie jest nieprawidłowe!')
        continue #ta instrukcja przenosi nas do początku pętli, więc nie wykona się ostatnia instrukcja
    win = isWin(user, goal) #wywołanie funkcji sprawdzającej, czy użytkownik wygrał przez porównanie user i goal,
                            #jeśli user == goal, to win = True i pętla przestaje się wykonywać - koniec gry

Powodzenia!

**Rozwiązanie**

In [15]:
from random import randint
from termcolor import colored

def generateNumber():
    return str(randint(1000, 9999))

def isWin(user, goal):
    return user == goal

def isCorrect(user, goal):
    ref = '1234567890'
    return len(user) == len(goal) and all([u in ref for u in user])

def showResult(user, goal):
    temp = [colored(u, 'green') if u == g else u for u, g in zip(user, goal)]
    print(*temp, sep = '', end = '\n')
    return True
    
goal = generateNumber()
win = False
while not win:    
    user = input('Wprowadź liczbę: ')
    if isCorrect(user, goal):
        showResult(user, goal)
    else:
        print('Podane wyrażenie jest nieprawidłowe!')
        continue
    win = isWin(user, goal)

Wprowadź liczbę: 1111
1111
Wprowadź liczbę: 2222
2222
Wprowadź liczbę: 3333
3333
Wprowadź liczbę: 4444
4444
Wprowadź liczbę: 5555
5555
Wprowadź liczbę: 6666
6666
Wprowadź liczbę: 7777
7777
Wprowadź liczbę: 8888
8888
Wprowadź liczbę: 3378
3378


In [16]:
from random import randint
from termcolor import colored

def generateNumber():
    return str(randint(1000, 9999))

def isWin(user, goal):
    return user == goal

def isCorrect(user, goal):
    ref = '1234567890'
    return len(user) == len(goal) and all([u in ref for u in user])

def showResult(user, goal):
    user = [[u, u == g, False] for u, g in zip(user, goal)]
    goal_reduced = [g for u, g in zip(user, goal) if not u[1]]
    for u in user:
        if not u[1] and u[0] in goal_reduced:
            u[2] = True
            goal_reduced.remove(u[0])
        else:
            pass    
    result = [colored(u[0], 'green') if u[1] else colored(u[0], 'yellow') if u[2] else u[0] for u in user]
    print(*result, sep = '', end = '\n')
    
goal = generateNumber()
win = False
while not win:    
    user = input('Wprowadź liczbę: ')
    if isCorrect(user, goal):
        showResult(user, goal)
    else:
        print('Podane wyrażenie jest nieprawidłowe!')
        continue
    win = isWin(user, goal)

Wprowadź liczbę: 123
Podane wyrażenie jest nieprawidłowe!
Wprowadź liczbę: 1234
1234
Wprowadź liczbę: 5678
5678
Wprowadź liczbę: 3890
3890
Wprowadź liczbę: 9938
9938
Wprowadź liczbę: 9338
9338


# Przydatne moduły

W tej części poznamy moduły przydatne przy wszelkiego rodzaju obliczeniach i prezentacji wyników. 

### NumPy

NumPy jest biblioteką przydatną w obliczeniach z wykorzystaniem wszelkiego rodzaju macierzy. Dzięki implementacji w języku C oraz C++ kod jest nawet 50x szybszy od napisanego za pomocą pythonowych list. Dodatkowo, zaimplementownych jest wiele funkcji, które ułatwiają i przyspieszają programowanie.

Import biblioteki odbywa się jak zwykle za pomocą instrukcji `import`

In [64]:
import numpy

Od tego momentu mamy dostęp do wszystkich zawartych w bibliotece funkcji i modułów. Podstawowym aspektem NumPy jest tworzenie obiektów `ndarray` czyli n-wymiarowych tablic (ndarray od n-dimensional array).

Przykład przekształcenia listy na `ndarray` korzystając z metody `array`:

In [67]:
L = [1, 2, 3]
arr = numpy.array(L)
type(arr)

numpy.ndarray

Ponieważ zwykle wpisywanie za każdym razem pełnej nazwy biblioteki przy metodzie jest uciążliwe (zwłaszcza dla dłuższych nazw), tę i wiele innych bibliotek można zaimportować nadając jej jednocześnie skróconą formę za pomocą wyrażenia `import <nazwa biblioteki> as <dowolna nazwa>`

In [2]:
import numpy as np

Tym sposobem, w celu stworzenia obiektu `ndarray` z listy możemy zamiast `numpy.array` zapisać `np.array`

In [72]:
L = [1, 2, 3]
arr = numpy.array(L)
type(arr)

numpy.ndarray

Obiekt `ndarray` obsługuje indeksowanie, tak samo jak inne sekwencje w Pythonie

In [68]:
arr[0]

1

In [69]:
arr[-1]

3

Jednak już na tym przykładzie można zauważyć wygodne różnice. Tablice `ndarray` w przeciwieństwie do list, możemy do siebie dodawać tak jak dodalibyśmy wektory

In [124]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
arr1 = np.array(l1)
arr2 = np.array(l2)

Listy składają się, więc tworzą jedną, dłuższą listę przy operacji `+`

In [74]:
l1 + l2

[1, 2, 3, 4, 5, 6]

Obiekty `ndarray` dodają odpowiednie elementy do siebie tak, jak to jest przy dodwaniu wektorów

In [125]:
arr1 + arr2

array([5, 7, 9])

W celu złożenia dwóch wektorów należy użyć metody `concatenate`

In [126]:
np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

Taka sama sytuacja występuje przy mnożeniu bądź dzieleniu.

In [76]:
l1 * 2

[1, 2, 3, 1, 2, 3]

In [77]:
arr1 * 2

array([2, 4, 6])

In [78]:
l1 / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [79]:
arr1 / 2

array([0.5, 1. , 1.5])

Spójrzmy teraz na te obiekty bardziej systematycznie.

**Wymiary**

Najprostrzą macierzą - 0-wymiarową jest liczba, oczywiście także w NumPy możemy je stworzyć 

In [81]:
arr0 = np.array(42)
arr0

array(42)

Macierz jednowymiarowa - wektor, poznaliśmy przed chwilą

In [82]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

Macierz dwuwymiarowa będzie tworzona za pomocą listy list (nawet wyświetlanie jest wygodne dla użytkownika)

In [116]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

Tak samo można tworzyć macierze o większej liczbie wymiarów. Trójwymiarowa 3x2x2 na przykład ma taką postać

In [86]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
arr3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

W celu sprawdzenia wymiaru danej macierzy możemy skorzystać z atrybutu przypisanego do każdej z nich `.ndim`

In [117]:
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


Mamy także dostęp do rozmiarów macierzy za pomocą atrybutu `.shape`

In [118]:
print(arr0.shape)
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

()
(3,)
(2, 3)
(3, 2, 2)


**Indeksowanie**

Indeksowanie jest znacznie wygodniejsze i pozwala na większą elastyczność w stosunku do list. Porównajmy dwie macierze 3x3 jedną stworzną za pomocą list i drugą `ndarray`

In [92]:
M = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Marr = np.array(M)
print(M)
print(Marr)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


W celu wyświetlenia elementu $m_{ij}$, gdzie $i$ to numer wiersza a $j$ to numer kolumny, dla list skorzystamy z zapisu (np. dla i=1, j=2)

In [93]:
M[0][1]

2

Podczas gdy NumPy pozwala nam na zapis za pomocą przecinka

In [95]:
Marr[0][1]

2

In [97]:
M[0, 1]

TypeError: list indices must be integers or slices, not tuple

In [96]:
Marr[0, 1]

2

Daje to nam przewagę, ponieważ jeśli z listy list chcemy wypisać pierwszą kolumnę to musimy skorzystać z funkcji `zip` i podawania argumentu z `*` tak jak było to opisane wcześniej

In [102]:
list(zip(*M))[0]

(1, 4, 7)

Podczas gdy `ndarray` pozwala nam skorzystać z zapisu z `:`

In [101]:
Marr[:, 0]

array([1, 4, 7])

Co oznacza, weź wszystkie elementy z pierwszego wymiaru i zerowe elementy z drugiego. Zobaczmy, że taki zapis dla list nie zadziała

In [104]:
M[:][0]

[1, 2, 3]

Czy jest zrozumiałe dlaczego?

Dzieki takiemu podejściu możemy w prosty sposób robić rzeczy, które na listach wymagałyby dłuższego zastanowienia, na przykład możemy wypisać macierz zawierającą co drugi element w wierszach i kolumnach

In [109]:
print(Marr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [110]:
print(Marr[::2, ::2])

[[1 3]
 [7 9]]


Możemy także zwrócić indeks/indeksy dla którego/których spełnione jest dowolne wyrażenie logiczne. Skorzystamy z funkcji `where`

In [6]:
arr = np.array([1, 2, 3, 4, 5, 2, 3, 2, 2, 1])
indices = np.where(arr == 2) #zwraca indeksy dla których wartość wektora arr wynosi 2
indices

(array([1, 4, 6, 7]),)

In [9]:
Marr = np.array([[1, 2, 3, 4, 5], [2, 3, 2, 2, 1]])
indices = np.where(Marr == 2) #zwraca indeksy dla których wartość macierzy arr wynosi 2
indices

(array([0, 1, 1, 1]), array([1, 0, 2, 3]))

Zwróćmy uwagę, że w przypadku macierzy pierwsza lista zwraca pierwszy indeks, a druga drugi, więc wartość 2 mają elementy:  

In [11]:
print(Marr[0, 1])
print(Marr[1, 0])
print(Marr[1, 2])
print(Marr[1, 3])

2
2
2
2


Wartości możemy także wyświetlić korzystając z indeksów bezpośrednio:

In [15]:
Marr[indices]

array([2, 2, 2, 2])

Ponieważ możemy korzystać z dowlnych wyrażen logicznych, nie sprawia trudności znalezienie np. elementów parzystych

In [17]:
even = np.where(Marr%2 == 0)
Marr[even]

array([2, 4, 2, 2, 2])

Lub nieparzystych

In [18]:
odd = np.where(Marr%2 == 1)
Marr[odd]

array([1, 3, 5, 3, 1])

Przydatnym zastosowaniem jest także znajdowanie indeksu wartości największej bądź najmniejszej 

In [134]:
import random as rnd
vec = np.array([rnd.randint(0, 100) for _ in range(10)]) #tworzymy losowy wektor
vec

array([98, 94, 77, 37, 54, 44, 91, 99, 83, 23])

In [135]:
min_index = np.where(vec == np.min(vec)) #korzystamy z funkcji min z biblioteki NumPy
max_index = np.where(vec == np.max(vec)) #korzystamy z funkcji max z biblioteki NumPy
print(min_index, max_index)
print(vec[min_index], vec[max_index])

(array([9]),) (array([7]),)
[23] [99]


**Inne przydatne funkcje**

W celu kopiowania obiektu możemy skorzystać z metody `.copy()`

In [23]:
Marr = np.array([[1, 2, 3],[4, 5, 6]])
Marr2 = Marr.copy()
Marr2[0, 0] = 100
print(Marr)
print(Marr2)

[[1 2 3]
 [4 5 6]]
[[100   2   3]
 [  4   5   6]]


Wektor można posortować za pomocą funkcji `sort`

In [26]:
vec = np.array([rnd.randint(0, 20) for _ in range(10)])
print(vec)
vec_sort = np.sort(vec)
print(vec_sort)

[17  4 11  4 12 17 15 16  0  7]
[ 0  4  4  7 11 12 15 16 17 17]


Sortować można także kilka list na raz (wiersze w macierzy)

In [27]:
Marr = np.array([[rnd.randint(0, 20) for _ in range(10)] for _ in range(3)])
print(Marr)
Marr_sort = np.sort(Marr)
print(Marr_sort)

[[15  1  9 12  0  0 20 13  8  9]
 [ 8  0 20 19  0 10 16  8 14 16]
 [13  6  7 10 17 11  1  5  4  0]]
[[ 0  0  1  8  9  9 12 13 15 20]
 [ 0  0  8  8 10 14 16 16 19 20]
 [ 0  1  4  5  6  7 10 11 13 17]]


Bardzo przydatne jest także tworzenie filtrów, które będą zwracać wartości spełniające określone wymagania

In [30]:
vec = np.array([rnd.randint(0, 10) for _ in range(5)])
print(vec)
x = [True, False, False, True, True] #filtr definiuje które wartości zachować, a które nie
print(x)
print(vec[x]) #filtr podajemy jako indeksy naszego wektora

[ 7  2 10  4  2]
[True, False, False, True, True]
[7 4 2]


Jak widać filtr odfiltorwał te indeksy, dla których wartość wynosiła `False`

**Przykłady zastosowań**

**Mnożenie macierzy**

W celu pomnożenia dwóch macierzy będących typu `ndarray` możemy skorzystać z wbudowanej funkcji `matmul`. Napiszmy krótki program pozwalający na porównanie czasów obliczeń iloczynu macierzy za pomocą biblioteki `numpy` i za pomocą list składanych.

Skorzystamy z biblioteki `time` zawierającej funkcję `time`, która zwraca (w sekundach) bieżący czas oraz funkcję `sleep`, która pozwala zatrzymać działanie na określony czas (podany w sekundach).

In [49]:
from time import time, sleep
t0 = time()
sleep(1) #czas oczekiwania podajemy w sekundach
t1 = time()
print(t0, t1, t1 - t0, sep = '\n')

1652187892.996225
1652187893.997749
1.0015239715576172


Zwróćmy dodatkowo uwagę na powyższy zapis ładowania modułu (biblioteki) `time`. Możemy z danej biblioteki pobrać tylko interesujące nas funkcje/ metody korzystając z formuły `from <biblioteka> import <nazwy funkcji po przecinku>`. W ten sposób nie musimy się odnosić do nazwy biblioteki, bo jej funkcje są dostępne bezpośrednio, wywoływane tylko za pomocą ich nazw. Można także załadować wszystkie dostępne w bibliotece rzeczy za pomocą wyrażenia `from <biblioteka> import *`. Należy jednak z tym uważać, gdyż niektóre nazwy funkcji/ metod mogą pokrywać się z innymi i w ten sposób nadpisywać się prowadząc do trudnych do wykrycia błędów.

Wróćmy do naszego programu porównującego czasy wykonywania mnożenia macierzy. Tak wygląda gotowy kod

In [137]:
import numpy as np
from time import time 
import random as rnd

Ns = [2, 10, 50, 100, 200, 400] #wymiary macierzy kwadratowej dla których będziemy dokonywać porównania

print(' N | list [ms]| numpy [ms] | ratio ' ) #tworzymy opis kolumn tabelki z wynikami

for N in Ns:
    A = [[rnd.random() for i in range(N)] for j in range(N)] #tworzymy macierz NxN losowych liczb rzeczywistych 
    Aarr = np.array(A) #tworzymy macierz ndarray
    
    t_0 = time()
    C = [[sum([a*b for a, b in zip(row_A, col_B)]) for col_B in zip(*A)] for row_A in A] #metoda list składanych
    t_list = time() - t_0

    t_0 = time()
    Carr = np.matmul(A, A) #metoda matmul z biblioteki NumPy
    t_numpy = time() - t_0

    print(str(N).center(3), str(np.round(t_list*1000, 2)).center(11), 
        str(np.round(t_numpy*1000, 2)).center(11), str(np.round(t_list/t_numpy, 2)).center(8)) #formatowanie wyświetlania

 N | list [ms]| numpy [ms] | ratio 
 2      1.06        0.04     29.65  
 10     0.09        0.03      3.64  
 50     7.22        0.22     32.61  
100    54.83        2.34     23.47  
200    416.05       2.46     169.03 
400   3620.62       9.38     386.08 


Jak widać kod w bibliotece `numpy` jest bardzo dobrze zoptymalizowany do tego typu działań. Dla macierzy 400x400 `matmul` działa nawet 300 razy szybciej.

**Sortowanie**

Analogicznie do poprzedniego przykładu, napiszmy program porównujący czasy sortowania metodą napisaną przez nas wcześniej - sortowania bąbelkowego, z metodą `sort` z biblioteki `numpy`.

Zaimportujmy najpier naszą funkcję do sortowania napisaną wcześniej.

In [61]:
def bubbleSort(L):
    n = len(L)
    while n > 1:
        for i in range(n - 1):
            if L[i] > L[i + 1]:
                L[i], L[i + 1] = L[i + 1], L[i]
            else:
                pass
        n -= 1
    return L

Stwórzmy wektor losowych wartości.

In [63]:
import numpy as np
import random as rnd

vec = np.array([rnd.randint(0, 100) for _ in range(10)])
vec

array([76, 81, 53, 83, 63, 47, 86, 77, 86, 95])

In [64]:
bubbleSort(vec)

array([47, 53, 63, 76, 77, 81, 83, 86, 86, 95])

**Uwaga!** Z powodu konstrukcji naszej funkcji `bubbleSort` wektor `vec` jest po takim wywołaniu posortowany, a nie pomieszany jak to miało miejsce na początku:

In [65]:
vec

array([47, 53, 63, 76, 77, 81, 83, 86, 86, 95])

Z tego powodu zamiast wywoływać funkcję z argumentem `vec`, skorzystajmy z jego kopii!

In [69]:
vec = np.array([rnd.randint(0, 100) for _ in range(10)])
vec

array([66, 45, 13, 66, 78, 63, 28,  4, 80, 27])

In [70]:
bubbleSort(vec.copy())

array([ 4, 13, 27, 28, 45, 63, 66, 66, 78, 80])

In [71]:
vec

array([66, 45, 13, 66, 78, 63, 28,  4, 80, 27])

Dzięki temu unikniemy nieprawdziwych wyników podczas pomiaru czasu, gdyż posortowana lista przejdzie przez sortowanie znacznie szybciej.

Cały program będzie więc wyglądał następująco

In [91]:
import numpy as np
from time import time 
import random as rnd

def bubbleSort(L):
    n = len(L)
    while n > 1:
        for i in range(n - 1):
            if L[i] > L[i + 1]:
                L[i], L[i + 1] = L[i + 1], L[i]
            else:
                pass
        n -= 1
    return L

print('  N  | bubble [ms]| numpy [ms] |  ratio ' )

Ns = [2, 10, 100, 500, 1000, 5000]
for N in Ns:
    vec = np.array([rnd.randint(0, 100) for _ in range(N)])
    
    t0 = time()
    bubbleSort(vec.copy())
    t_bubble = time() - t0
    
    t0 = time()
    np.sort(vec.copy())
    t_sort = time() - t0

    print(str(N).center(5), str(np.round(t_bubble*1000, 2)).center(13), 
        str(np.round(t_sort*1000, 2)).center(12), str(np.round(t_bubble/t_sort, 2)).center(8))

  N  | bubble [ms]| numpy [ms] |  ratio 
  2        0.03         0.02       1.17  
  10       0.04         0.01       2.52  
 100       1.76         0.01      160.26 
 500      44.31         0.04     1264.37 
 1000     172.76        0.05      3418.0 
 5000    4371.17        0.16     26532.6 


Jak widać w tym przypadku dla dłuższych list czas sortowania metodą `sort` jest nieprawdopodobnie krótszy (tysiące razy) od sortowania bąbelkowego.

W powyższych programach na końcu skorzystaliśmy z nieomówionej funkcji `round`. Służy ona do zaokrąglania liczb do określonej liczby miejsc po przecinku.

In [139]:
liczba = 123.4567

In [140]:
np.round(liczba, 1)

123.5

In [141]:
np.round(liczba, 2)

123.46

In [142]:
np.round(liczba, 3)

123.457

**Zadanie domowe!**

Rozwiązywanie układów równań liniowych metodą eliminacji Gaussa.<br>

Weźmy przykładowy układ równań i rozwiążmy go metodą eliminacji. Oznaczmy przez $w_i$ $i$-te równanie, opis nad strzałkami informajue jakie transformacje zostały przeprowadzone:<br>

$
\left\{
\begin{aligned}
2x_1 + 4x_2 - 2x_3 &= 4\\
1x_1 - 2x_2 + 1x_3 &= 0\\
4x_1 - 1x_2 - 1x_3 &= -1\\
\end{aligned}
\right.
\xrightarrow{\substack{w_1 \rightarrow w_1\\w_2 \rightarrow w_2 - \frac{1}{2} w_1\\w_3 \rightarrow w_3 - 2w_1}}
\left\{
\begin{aligned}
2x_1 + 4x_2 - 2x_3 &= 4\\
0x_1 - 4x_2 + 2x_3 &= -2\\
0x_1 - 9x_2 + 3x_3 &= -9\\
\end{aligned}
\right. 
\xrightarrow{\substack{w_1 \rightarrow w_1\\w_2 \rightarrow w_2\\w_3 \rightarrow w_3 - \frac{9}{4}w_2}}
\left\{
\begin{aligned}
2x_1 + 4x_2 - 2x_3 &= 4\\
0x_1 - 4x_2 + 2x_3 &= -2\\
0x_1 + 0x_2 - \frac{3}{2}x_3 &= -\frac{9}{2}\\
\end{aligned}
\right.
$<br>
Doprowadziliśmy do sytuacji w której ostatnie równanie zawiera tylko jedną niewiadomą $x_3$, możemy je więc rozwiązać. Następnie $x_3$ wykorzystamy do znalezienia $x_2$ z równania drugiego. Znalezione $x_3$ oraz $x_2$ posłużą z kolei do znalezienia $x_1$ co kończy szukanie rozwiązań:<br>
$
\left\{
\begin{aligned}
x_1 &= 1\\
x_2 &= 2\\
x_3 &= 3\\
\end{aligned}
\right.
$

Zauważmy, że powyższy sposób jest usystematyzowaną metodą. Dodatkowo, nie musimy cały czas ciągnąć zmiennych za sobą, możemy czynniki przepisać w formie tak zwanej macierzy rozszerzonej, gdzie ostatnia kolumna to wyrazy wolne z równań (dla podkreślenia odrębności jest oddzielona kreską):<br>

$
\left( \begin{array}{ccc|c}
2 & 4 & -2 & 4 \\
1 & -2 & 1 & 0 \\
4 & -1 & -1 & -1 
\end{array} \right) \xrightarrow{\substack{w_1 \rightarrow w_1\\w_2 \rightarrow w_2 - \frac{1}{2} w_1\\w_3 \rightarrow w_3 - 2w_1}}
\left( \begin{array}{ccc|c}
2 & 4 & -2 & 4 \\
0 & -4 & 2 & -2 \\
0 & -9 & 3 & -9 
\end{array}\right) \xrightarrow{\substack{w_1 \rightarrow w_1\\w_2 \rightarrow w_2\\w_3 \rightarrow w_3 - \frac{9}{4}w_2}}
\left( \begin{array}{ccc|c}
2 & 4 & -2 & 4 \\
0 & -4 & 2 & -2 \\
0 & 0 & -\frac{3}{2} & -\frac{9}{2} 
\end{array} \right)
$<br>
Poprzez dodawnie i odejmowanie odpowiednich wierszy doprowadziliśmy macierz do postaci tórjkątnej. 

Ponieważ w celu znalezienia rozwiązań najpierw należy doprowadzić macierz do postaci trójkątnej **zadanie polega na stworzeniu funkcji `triangle`**, która podaną poprzez argument macierz doprowadzi do takiej postaci za pomocą dodawania i odejmowania odpowiednich wierszy przemonożonych przez współczynnik.

Rozpatrzmy przypadek ogólny macierzy $N\times N$podstaci <br>
$
A = \left( \begin{array}{cccc|c}
a_{11} & a_{12} & \cdots & a_{1N} & b_1 \\
a_{21} & a_{22} & \cdots & a_{2N} & b_2 \\
\vdots  & \vdots  & \ddots & \vdots & \vdots\\
a_{N1} & a_{N2} & \cdots & a_{NN} & b_N 
\end{array} \right)    
$<br>
W pierwszym kroku algorytmu Gaussa będziemy od każdego wiersza (poza pierwszym) odejmować wiersz pierwszy pomnożony przez czynnik $-\frac{a_{i1}}{a_{11}}$, tym sposobem pierwsze elementy w każdym wierszu poniżej pierwszego wyzerują się:
1. $w_i \rightarrow w_i-\frac{a_{i1}}{a_{11}}w_1$, dla $i>1$.<br>

W wyniku dostajemy macierz postaci<br>
$
A = \left( \begin{array}{cccc|c}
a_{11} & a_{12} & \cdots & a_{1N} & b_1 \\
0 & a_{22}-\frac{a_{21}}{a_{11}}a_{12} & \cdots & a_{2N}- \frac{a_{21}}{a_{11}}a_{1N}& b_2- \frac{a_{21}}{a_{11}}b_1 \\
\vdots  & \vdots  & \ddots & \vdots & \vdots\\
0 & a_{N2}- \frac{a_{N1}}{a_{11}}a_{12} & \cdots & a_{NN}- \frac{a_{N1}}{a_{11}}a_{1N} & b_N - \frac{a_{N1}}{a_{11}}b_1
\end{array} \right)
$

=\left( \begin{array}{cccc|c}
a_{11} & a_{12} & \cdots & a_{1N} & b_1 \\
0 & a'_{22} & \cdots & a'_{2N} & b'_2 \\
\vdots  & \vdots  & \ddots & \vdots & \vdots\\
0 & a'_{N2} & \cdots & a'_{NN} & b'_N 
\end{array} \right),
$

gdzie przepisaliśmy elementy zmienione na primowane o takich samych indeksach jak poprzednio.

W drugim kroku robimy dokładnie to samo, ale dla macierzy zmniejszonej (tej z elementami primowanymi). Więc tym razem odejmować będziemy drugi wiersz, a czynnik będzie opierał się na drugich elementach:<br>
2. $w'_i \rightarrow w'_i - \frac{a'_{i2}}{a'_{22}}w'_2$, dla $i>2$.<br>

W wyniku dostajemy zera w drugiej kolumnie zaczynając od wiersza trzeciego.<br>
Procedurę powtarzamy aż do kroku numer $N-1$. Na końcu mamy macierz trójkątną.    

**Uwaga!** Procedura opiera się na dzieleniu przez elementy $a_{11}$, $a'_{22}$, $a''_{33}$ itd., dlatego nie mogą one być zerami! **Jeśli w którymś momencie element przez który dzielimy będzie zerem, funkcja powinna zwrócić wartość `False`**, co zakończy działanie - nie znajdziemy rozwiązań pomimo że mogą one istnieć. Problem ten rozwiążemy następnym razem.

**Uwaga!** Ponieważ w zadaniu chcemy mieć tyle samo równań co niewiadomych, dołóżmy także wymaganie jednoznaczności rozwiązań, co oznacza, że wszystkie wiersze są liniowo niezależne. **Jeśli rząd macierzy jest za mały, należy zwrócić wartość `False`**. Bardziej ogólny przypadek omówimy później. Sprawdzenia, czy układ posiada rozwiązanie jednoznaczne moża dokonać licząc rząd macierzy - jeśli rząd jest równy wymiarowi bez ostatniej kolumny ($\text{rank}(A)=N$), istnieje jednoznaczne rozwiązanie. Dla uproszczenia zadania, rząd możemy sprawdzić za pomocą funkcji `linalg.matrix_rank` z biblioteki NumPy

In [8]:
A = np.array([[1, 2], [3, 4]]) #macierz z liniowo niezależnymi wierszami - rząd 2
B = np.array([[1, 2, 3], [2, 4, 6]]) #macierz z liniowo zależnymi wierszami - rząd 1
rankA = np.linalg.matrix_rank(A)
rankB = np.linalg.matrix_rank(B)
print(A)
print('Rząd A =', rankA)
print(B)
print('Rząd B =', rankB)

[[1 2]
 [3 4]]
Rząd A = 2
[[1 2 3]
 [2 4 6]]
Rząd B = 1


Przykład działania.<br>

In [18]:
M = np.array([[2., 1., 1., 1., 0.], [-1., -2., -1., 1., 1.], [1., 1., -2., -3., 2.], [4., -2., 0., 4., 2.]])
print(M)
print(triangle(M))

[[ 2.  1.  1.  1.  0.]
 [-1. -2. -1.  1.  1.]
 [ 1.  1. -2. -3.  2.]
 [ 4. -2.  0.  4.  2.]]
[[ 2.         1.         1.         1.         0.       ]
 [ 0.        -1.5       -0.5        1.5        1.       ]
 [ 0.         0.        -2.6666667 -3.         2.3333333]
 [ 0.         0.         0.        -1.25      -1.25     ]]


In [23]:
M = np.array([[2., 1., 1., 1., 0.], [4., 2., 2., 2., 0.], [1., 1., -2., -3., 2.], [4., -2., 0., 4., 2.]])
print(M)
print(triangle(M))

[[ 2.  1.  1.  1.  0.]
 [ 4.  2.  2.  2.  0.]
 [ 1.  1. -2. -3.  2.]
 [ 4. -2.  0.  4.  2.]]
False


**Uwaga!** W celu uniknięcia subtelnych problemów, polecam czynniki zapisywać zawsze w formie zmiennoprzecinkowej (z kropką).

Powodzenia!